---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      name: db-pod
      labels:
        app: backend
    spec:
      containers:
        - name: db-container
          image: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "prince"
            - name: MYSQL_DATABASE
              value: "prince"
---

apiVersion: v1
kind: Service
metadata:
  name: dbsvc
spec:
  selector:
    app: backend
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306

