---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-deploy
spec:
  replicas: 5
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      name: wp-pod
      labels:
        app: frontend
    spec:
      containers:
        - name: wp-container
          image: wordpress
          env:
            - name: WORDPRESS_DB_NAME
              value: "prince"
            - name: WORDPRESS_DB_USER
              value: "root"
            - name: WORDPRESS_DB_PASSWORD
              value: "prince"
            - name: WORDPRESS_DB_HOST
              value: "dbsvc"
---

apiVersion: v1
kind: Service
metadata:
  name: wpsvc
spec:
  selector:
    app: frontend
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080

